from odoo import models
import arabic_reshaper
from bidi.algorithm import get_display

class SignRequestItem(models.Model):
    _inherit = 'sign.request.item'

    # Note: You have to override the specific Odoo 17 method that draws the text on the PDF.
    # Usually, this is injected before the reportlab library stamps the text.
    def _get_pdf_values(self):
        # We get the original values generated by Odoo
        res = super(SignRequestItem, self)._get_pdf_values()
        
        # Loop through the values and reshape any Arabic text
        if 'value' in res and res['value']:
            try:
                # 1. Reshape the letters so they connect properly
                reshaped_text = arabic_reshaper.reshape(res['value'])
                # 2. Reorder them from Right-to-Left
                bidi_text = get_display(reshaped_text)
                res['value'] = bidi_text
            except Exception as e:
                pass
                
        return res
